---
# Source: base/templates/configmap-ini.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: qm-ini
data:
  qm.ini: |-
    LogDefaults:
       LogPrimaryFiles=3
       LogSecondaryFiles=2
       LogFilePages=4096
       LogType=CIRCULAR
       LogBufferPages=0
       LogDefaultPath=/var/mqm/log
---
# Source: base/templates/configmap-mqsc.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: qm-mqsc
data:
  qm.mqsc: |-
    DEFINE QLOCAL('Q1') REPLACE DEFPSIST(YES)
    DEFINE CHANNEL(EXT.CONN) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER')
    SET CHLAUTH(EXT.CONN) TYPE(BLOCKUSER) USERLIST('nobody') ACTION(ADD)
