---
# Source: base/templates/configmap-ini.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: qm-ini
  namespace: mq
data:
---
# Source: base/templates/configmap-mqsc.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: qm-mqsc
  namespace: mq
data:
  qm.mqsc: "DEFINE QLOCAL('IN') REPLACE \nDEFINE CHANNEL(EXT.CONN.ROUTE) CHLTYPE(SVRCONN)
    TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER')\nSET CHLAUTH(EXT.CONN.ROUTE)
    TYPE(BLOCKUSER) USERLIST('nobody') ACTION(ADD)"
  test.mqsc: |-
    DEFINE QLOCAL(test-queue) REPLACE DEFPSIST(YES)
    DEFINE CHANNEL(EXT.CONN) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER')
    SET CHLAUTH(EXT.CONN) TYPE(BLOCKUSER) USERLIST('nobody') ACTION(ADD)
