apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: qm2-ext-conn-traffic
spec:
  host: ext2e-conn.chl.mq.ibm.com
  to:
    kind: Service
    name: qm-2-ibm-mq
  port:
    targetPort: 1414
  tls:
    termination: passthrough
