apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: qm1
spec:
  license:
    accept: true
    license: L-RJON-C7QG3S
    metric: VirtualProcessorCore
    use: NonProduction
  web:
    enabled: true
  version: 9.2.4.0-r1
  queueManager:
    name: QUICKSTART
    mqsc:
      - configMap:
          name: qm-mqsc
          items:
            - qm.mqsc
    availability:
      type: SingleInstance
      updateStrategy: RollingUpdate
    storage:
      queueManager:
        type: ephemeral
