apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: qm1-ext-conn-traffic
spec:
# EXT.CONN.ROUTE
  host: ext2e-conn2e-route.chl.mq.ibm.com
  to:
    kind: Service
    name: qm-1-ibm-mq
  port:
    targetPort: 1414
  tls:
    termination: passthrough
